project:
  type: website
  execute-dir: project

website:
  title: "LALLPI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/people.qmd
        text: Team

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">