project:
  type: website
  execute-dir: project

website:
  title: "LALLPI"
  image: images/favicon.svg    # For social-network sharing
  favicon: images/favicon.svg
  twitter-card: true           # Twitter card metadata
  open-graph: true             # For social-network sharing
  llms-txt: true               # LLM (large language model) output
  site-url: lallpi.netlify.app # For social-network sharing
  search:
    location: navbar
    type: overlay
  google-analytics: "G-VME9FKJ138"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/data.qmd
        text: Data
      - href: pages/documentation.qmd
        text: Documentation
      - href: pages/countries.qmd
        text: Countries
      - href: pages/team.qmd
        text: Team
      - href: pages/citation.qmd
        text: Citation
    right:
      - icon: github
        href: https://github.com/ncachanosky/LALLPI
        aria-label: GitHub repository
  page-footer:
    left: |
      &copy; 2025 Nicolas Cachanosky, João P. Bastos, Alexandre Padilla
    background: "#041E42"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">